server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/batch?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: create

  batch:
    job:
      name: ${job.name:NONE}
    jdbc:
      initialize-schema: always

logging:
  level:
    org:
      hibernate:
        SQL: debug   # SQL ?? ??
        type:
          descriptor:
            sql: trace  # SQL ?????? ??
